app/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_user, logout_user, login_required
from werkzeug.security import check_password_hash, generate_password_hash
from app.models import User
from app import db

auth_bp = Blueprint('auth', __name__, url_prefix='/auth')

@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']

        user = User.query.filter_by(username=username).first()

        if user and check_password_hash(user.password, password):
            login_user(user)
            flash('Logged in successfully.', 'success')
            return redirect(url_for('products.get_products'))
        else:
            flash('Invalid username or password.', 'error')

    return render_template('login.html')

@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('Logged out.', 'info')
    return redirect(url_for('auth.login'))

@auth_bp.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        
        # Check if user exists
        existing_user = User.query.filter_by(username=username).first()
        # TODO Make live username checker later
        if existing_user:
            flash('Username already taken', 'error')
            return redirect(url_for('auth.register'))
        
        # Create new user
        hashed_password = generate_password_hash(password)
        new_user = User(username=username, password=hashed_password)
        db.session.add(new_user)
        db.session.commit()

        login_user(new_user)
        flash('Account created. Welcome', 'success')
        return redirect(url_for('main.home'))
    
    return render_template('register.html')

app/routes/cart.py
from flask import Blueprint, session, redirect, url_for, request, flash, render_template
from app.models import Product
from app.extensions import db

cart_bp = Blueprint('cart', __name__, url_prefix='/cart')

@cart_bp.route('/add_to_cart/<int:product_id>', methods=['POST'])
def add_to_cart(product_id):
    cart = session.get('cart', {})

    if str(product_id) in cart:
        cart[str(product_id)] += 1
    else:
        cart[str(product_id)] = 1

    session['cart'] = cart
    flash('Product added to cart!', 'success')
    return redirect(request.referrer or url_for('main.index'))

@cart_bp.route('/')
def view_cart():
    cart = session.get('cart', {})
    product_ids = list(map(int, cart.keys()))

    products = Product.query.filter(Product.id.in_(product_ids)).all()

    cart_items = []
    total_price = 0

    for product in products:
        quantity = cart[str(product.id)]
        cart_items.append({
            'product': product,
            'quantity': quantity
        })
        total_price += product.price * quantity

    return render_template('cart.html', cart_items=cart_items, total_price=total_price)

@cart_bp.route('/updated/<int:product_id>', methods=['POST'])
def update_cart(product_id):
    cart = session.get('cart', {})
    product_id_str = str(product_id)
    quantity = request.form.get('quantity', type=int)

    if quantity is None or quantity < 1:
        flash('Invalid quantity.', 'error')
        return redirect(url_for('cart.view_cart'))
    
    if product_id_str in cart:
        cart[product_id_str] = quantity
        session['cart'] = cart
        flash('Cart updated!', 'success')
    else:
        flash('Product not found in cart.', 'error')

    return redirect(url_for('cart.view_cart'))


@cart_bp.route('/remove/<int:product_id>', methods=['POST'])
def remove_from_cart(product_id):
    cart = session.get('cart', {})

    product_id_str = str(product_id)
    if product_id_str in cart:
        del cart[product_id_str]
        session['cart'] = cart
        flash('Product removed from cart!', 'success')
    else: 
        flash('Product not found in cart.', 'error')


    return redirect(url_for('cart.view_cart'))

app/routes/orders.py
from flask import Blueprint, render_template, request, redirect, url_for, session, flash
from app.extensions import db
from app.models import Product, Order, OrderItem

orders_bp = Blueprint('orders', __name__, url_prefix='/orders')

@orders_bp.route('/checkout', methods=['GET', 'POST'])
def checkout():
    cart = session.get('cart', {})
    cart_items = []
    total_price = 0

    for product_id, quantity in cart.items():
        product = Product.query.get(int(product_id))
        if product:
            cart_items.append({'product': product,'quantity': quantity})
            total_price += product.price * quantity

    if request.method == 'POST':
        customer_name = request.form.get('name')
        customer_email = request.form.get('email')

        if not customer_name or not customer_email:
            flash("Please enter both name and email!", 'error')
            return render_template('checkout.html', cart_items=cart_items, total_price=total_price)
        
        order = Order(customer_name=customer_name, customer_email=customer_email)
        db.session.add(order)
        db.session.flush()

        for item in cart_items:
            order_item = OrderItem(
                order_id=order.id,
                product_id=item['product'].id,
                quantity=item['quantity'],
                unit_price=item['product'].price
            )
            db.session.add(order_item)
        
        db.session.commit()
        session.pop('cart', None)
        flash("Order placed successfully!", 'success')
        return redirect(url_for('orders.confirmation'))
    
    return render_template('checkout.html', cart_items=cart_items, total_price=total_price)

@orders_bp.route('/confirmation')
def confirmation():
    return render_template('confirmation.html')

app/routes/products.py
from flask import Blueprint, jsonify, request, abort
from flask_login import current_user, login_required
from app.models import Product
from app import db

products_bp = Blueprint('products', __name__, url_prefix='/products')

products_bp.route('/', methods=['POST'])
@login_required
def create_product():
    if not current_user.is_authenticated:
        abort(401)

    data = request.get_json()
    name = data.get('name')
    price = data.get('price')
    description = data.get('description', '')
    image_url = data.get('image_url', '')

    if not name or price is None:
        abort(400, 'Missing required fields')

    new_product = Product(
        name=name,
        price=price,
        description=description,
        image_url=image_url
    )
    db.session.add(new_product)
    db.session.commit()

    return jsonify({'message': 'Product created', 'id': new_product.id}), 201



@products_bp.route('/', methods=['GET'])
def get_products():
    query = Product.query

    name = request.args.get('name')
    min_price = request.args.get('min_price', type=float)
    max_price = request.args.get('max_price', type=float)

    # Apply filters
    if name:
        query = query.filter(Product.name.ilike(f'%{name}%'))
    if min_price is not None:
        query = query.filter(Product.price >= min_price)
    if max_price is not None:
        query = query.filter(Product.price <= max_price)

    products = query.all()

    products_list = []
    for product in products:
        products_list.append({
            'id': product.id,
            'name': product.name,
            'description': product.description,
            'price': product.price,
            'image_url': product.image_url
        })

    return jsonify(products_list)


@products_bp.route('/<int:id>', methods=['GET'])
def get_product(id):
    product = Product.query.get_or_404(id)
    return jsonify({
        'id': product.id,
        'name': product.name,
        'description' : product.description,
        'price' : product.price,
    })

@products_bp.route('/<int:id>', methods=['PUT', 'PATCH'])
@login_required
def update_product(id):
    product = product.query.get_or_404(id)

    data = request.get_json()
    name = data.get('name')
    price = data.get('price')
    description = data.get('description')
    image_url = data.get('image_url')

    if name:
        product.name = name
    if price is not None:
        product.price = price
    if description is not None: 
        product.description = description
    if image_url is not None:
        product.image_url = image_url
    
    db.session.commit()

    return jsonify({'message': 'Product updated', 'id': product.id})


@products_bp.route('/<int:id>', methods=['DELETE'])
@login_required
def delete_product(id):
    product = Product.query.get_or_404(id)

    db.session.delete(product)
    db.session.commit()

    return jsonify({'message': 'Product deleted', 'id': id})

app/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF_8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content=<!-- TODO: SEO: page description --> >
    <meta name="keywords" content=<!-- TODO: SEO keywords --> >
    <meta name="author" content=<!-- TODO: Author info --> >
    <title>{% block title %}Gin Webshop{% endblock %}</title>
    <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}" type="image/x-icon"> <!-- Icon in browser tab -->
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
</head>
<body>
    <nav>
        <a href="{{ url_for('main.index') }}">Home</a>

    {% if current_user.is_authenticated %}
    <a href="{{ url_for('auth.logout') }}">Logout</a>
    {% else %}
    <a href="{{ url_for('auth.login') }}">Login</a>
    {% endif %}
    </nav>

    <main>
    {% block content %}{% endblock %}
    </main>

    <footer>
    <!-- footer -->
    </footer>
</body>
</html>

app/templates/cart.html
{% extends 'base.html' %}

{% block title %}Your Cart{% endblock %}

{% block content %}
    <h1>Your Shopping Cart</h1>

    {% if cart_items %}
        <ul>
            {% for item in cart_items %}
                <li>
                    {{ item.product.name}} - {{ item.quantity}} x {{ item.product.price}} Ft

                    <!-- Update quantity form -->
                    <!-- TODO CSRF protection -->
                    <form action="{{ url_for('cart.update_cart', product_id=item.product.id) }}" method="POST" style="display:inline-block; margin-left: 20px;">
                        <input type="number" name="quantity" value="{{ item.quantity }}" min="1" style="width: 60px;">
                        <button type="submit">Update</button>
                    </form>

                    <!-- Remove product form -->
                    <!-- TODO CSRF protection -->
                    <form action="{{ url_for('cart.remove_from_cart', product_id=item.product.id) }}" method="POST" style="display:inline-block; margin-left: 10px;">
                        <button type="submit" onclick="return confirm('Are you sure you want to remove this item?');">Remove</button>
                    </form>
                </li>
            {% endfor %}
        </ul>
        <p><strong>Total: {{ total_price }} Ft</strong></p>
        <a href="#" class="">Proceed to Checkout</a>
    {% else %}
        <p>Your cart is empty. Go grab some gin!</p>
    {% endif %}
{% endblock %}

app/templates/checkout.html
{% extends 'base.html' %}

{% block title %}Checkout - Gin Webshop{% endblock %}

{% block content %}
<h1>Checkout</h1>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
{% endwith %}

{% if cart_items %}
    <table>
        <thead>
            <tr>
                <th>Product</th>
                <th>Quantity</th>
                <th>Price (each)</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            {% for item in cart_items %}
            <tr>
                <td>{{ item.product.name }}</td>
                <td>{{ item.quantity }}</td>
                <td>{{ item.product.price }} Ft</td>
                <td>{{ (item.product.price * item.quantity) | round(2) }} Ft</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <h3>Total Price: {{ total_price | round(2) }} Ft</h3>

    <form method="POST" action="{{ url_for('orders.checkout') }}">
        <div>
            <label for="name">Name:</label>
            <input type="text" id="name" name="name" required />
        </div>

        <div>
            <label for="email">Email:</label>
            <input type="email" id="email" name="email" required />
        </div>

        <button type="submit">Place Order</button>
    </form>

{% else %}
    <p>Your cart is empty.</p>
    <a href="{{ url_for('products.products') }}">Go back to products</a>
{% endif %}

{% endblock %}

app/templates/confirmation.html
{% extends 'base.html' %}

{% block title %}Order Confirmation - Gin Webshop{% endblock %}

{% block content %}
    <h1>Thank you for your order!</h1>
    <p>Your gin is now on its way to your taste buds. 🍸</p>
    <p>You’ll receive an email confirmation shortly with your order details.</p>
    <a href="{{ url_for('main.index') }}">Back to homepage</a>
{% endblock %}

app/templates/login.html
{% extends 'base.html' %}

{% block title %}Login or Register{% endblock %}

{% block content %}
<h2>Login</h2>

{% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
        <p class="{% if category == 'error' %}text-error{% elif category == 'success' %}text-success{% else %}text-info{% endif %}">
        {{ message }}
        </p>
    {% endfor %}
    {% endif %}
{% endwith %}

<!-- Login Form -->
<form method="POST" action="{{ url_for('auth.login') }}">
    <label>Username:</label>
    <input type="text" name="username" required><br>

    <label>Password:</label>
    <input type="password" name="password" required><br>

    <button type="submit">Login</button>
</form>

<hr>

<!-- Register Form -->
<h2>Register</h2>
<form method="POST" action="{{ url_for('auth.register') }}">
    <label>Username:</label>
    <input type="text" name="username" required><br>

    <label>Password:</label>
    <input type="password" name="password" required><br>

    <button type="submit">Register</button>
</form>

{% endblock %}

app/templates/products.html
{% extends 'base.html' %}

{% block title %}Gin Webshop{% endblock %}

{% block content %}
    <h1>Available Gins</h1>

    <div class="product-grid">
    {% for product in products %}
        <div class="product-card">
            <img src="{{ product.image_url }}" alt="{{ product.name }}" width="150">
            <h3>{{ product.name }}</h3>
            <p>{{ product.description }}</p>
            <strong>{{ product.price }} Ft</strong>

            <form action="{{ url_for('cart.add_to_cart', product_id=product.id) }}" method="POST"> <!-- TODO CSRF protection -->
                <input type="hidded" name="quantity" value="1">
                <button type="submit">Add to Cart</button>
            </form>
        </div>
    {% endfor %}
    </div>
{% endblock %}